name: Deploy multiple static sites to Pages

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Combine both sites
        run: |
          mkdir combined
          cp -r ws2025/* combined/
          mkdir combined/eng
          cp -r ws2025eng/* combined/eng/

      - name: Upload combined artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'combined'
          name: 'github-pages'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
